### ISSUE TITLE
Method eth_submitHasrate

### ISSUE THREAD

**Issue by MonkeyD-Core** [barrystyle/yiimp-kawpow#1]
![image](https://user-images.githubusercontent.com/62377315/189838659-686f8112-e881-4bf7-9726-e54fee5b9bc0.png)

Any idea ?

**Comment by jakubartur** [comment]
me testing stratum mining work , only not fund blok , teamredminer no work miner error rpc

**Comment by barrystyle** [comment]
eth_submitHashrate is a json method that the miner uses, to inform the stratum what hashrate is being generated.
since we can't trust it (you could set it to anything), we simply ignore it.

unknown method does not indicate an error.
